algorithm: "drr"
model_train:
    users_num: 1083
    items_num: 38333
    embedding_dim: 50
    state_size: 5
    srm_size: 3
    max_eps_num: 10000
    actor_hidden_dim: 512
    actor_learning_rate: 0.0001
    critic_hidden_dim: 512
    critic_learning_rate: 0.001
    discount_factor: 0.5
    tau: 0.01
    learning_starts: 1000
    replay_memory_size: 1000000
    batch_size: 64
    embedding_network_weights: model/pmf/foursquare_emb_50_ratio_0.800000_bs_1000_e_789_wd_0.100000_lr_0.000100_trained_pmf.pt
    use_reward_model: false
    n_groups: 10
    done_count: 10
    fairness_constraints: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    reward_threshold: 1.0
    reward_version: paper