emb_train:
    max_epoch: 150
    init_user_batch_size: 32
    final_user_batch_size: 1024
    users_num: 943
    items_num: 1682
    embedding_dim: 50

model_train:
    algorithm: "fairrec"
    users_num: 943
    items_num: 1682
    state_size: 5
    srm_size: 6
    max_eps_num: 1000
    embedding_dim: 50
    actor_hidden_dim: 128
    actor_learning_rate: 0.001
    critic_hidden_dim: 128
    critic_learning_rate: 0.001
    discount_factor: 0.9
    tau: 0.001
    replay_memory_size: 1000000
    batch_size: 32
    embedding_network_weights: user_movie_at_once.h5
    n_groups: 10
    fairness_constraints: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
