users_num: 6041
items_num: 3953
state_size: 10
max_eps_num: 15000
embedding_dim: 100
actor_hidden_dim: 512
actor_learning_rate: 0.001
critic_hidden_dim: 512
critic_learning_rate: 0.001
discount_factor: 0.9
tau: 0.001
replay_memory_size: 1000000
batch_size: 1024
embedding_network_weights: user_movie_at_once.h5
fairness_constraints: [0.25, 0.25, 0.25, 0.25]
