algorithm: "drr"
model_train:
    users_num: 26306
    items_num: 11972
    embedding_dim: 50
    state_size: 2
    srm_size: 3
    max_eps_num: 10000
    actor_hidden_dim: 256
    actor_learning_rate: 0.0001
    critic_hidden_dim: 256
    critic_learning_rate: 0.001
    discount_factor: 0.9
    tau: 0.01
    learning_starts: 1000
    replay_memory_size: 1000000
    batch_size: 32
    embedding_network_weights: model/pmf/trivago_emb_50_ratio_0.800000_bs_1000_e_367_wd_0.100000_lr_0.000100_trained_pmf.pt
    use_reward_model: true
    n_groups: 10
    done_count: 5
    fairness_constraints: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    reward_threshold: 1.0