algorithm: "drr"
model_train:
    users_num: 43938
    items_num: 4292
    embedding_dim: 100
    state_size: 5
    srm_size: 3
    max_eps_num: 26000
    actor_hidden_dim: 512
    actor_learning_rate: 0.0001
    critic_hidden_dim: 512
    critic_learning_rate: 0.001
    discount_factor: 0.9
    tau: 0.01
    learning_starts: 5000
    replay_memory_size: 100000
    batch_size: 64
    embedding_network_weights: model/pmf/yelp_fl_emb_100_ratio_0.800000_bs_100000_e_379_wd_0.100000_lr_0.000100_trained_pmf.pt
    use_reward_model: true
    n_groups: 10
    done_count: 10
    fairness_constraints: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    reward_threshold: 4.0
    reward_version: attention
    user_intent_threshold: 0
    user_intent:  none